platform :ios, '14.0'

target 'MyHostApp' do
  use_frameworks!
  use_modular_headers!

  flutter_application_path = '../my_flutter_module'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
  install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end